apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: final
  labels:
    app: app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      version: v1
  template:
    metadata:
      labels:
        app: app
        version: v1
    spec:
      serviceAccountName: clo835-serviceaccount
      containers:
        - name: webapp
          image: 168491602991.dkr.ecr.us-east-1.amazonaws.com/clo835-finalproject-pg:WebAPP-20240415225840
          ports:
            - containerPort: 8080
          env: 
            - name: DBPORT
              value: "3306"
            - name: DBHOST
              value: "mysql-service.final.svc.cluster.local"
            - name: DBUSER
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: username  
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: dbsecret
                  key: pwd
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: img-config
                  key: image_url
            - name: GROUP_NAME
              value: "Group-1"
            - name: SLOGAN
              value: "This project was done by Mike and Prason."
      imagePullSecrets:
        - name: imagepullsecret
