kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pv-claim
  namespace: final
  labels:
    app: sql-pvc
spec:
  storageClassName: storageclass-clo835
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
