apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-clo835
  namespace: final
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer