kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: my-pvc
  namespace: final
  labels:
    app: sql-pvc
spec:
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
