apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: final
  labels:
    app: app
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
      version: v1
  template:
    metadata:
      labels:
        app: app
        version: v1
    spec:
      containers:
      - name: webapp
        image: 168491602991.dkr.ecr.us-east-1.amazonaws.com/webapp:v1
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: mypasswordapp
        env: 
          - name: DBPORT
            value: "3306"
          - name: DBHOST
            value: "192.168.88.19"