name: Deploy to ECR

on: 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:
    
    - name: Check out code
      uses: actions/checkout@v2
      
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: Build, test, tag, and push MySQL image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: clo835-finalproject-pg
        #IMAGE_TAG: v0.2
      run: |
        # Generate IMAGE_TAG using current date and time
        IMAGE_TAG=mysql-$(date +"%Y-%m-%d-%H%M%S")
        echo "IMAGE_TAG: $IMAGE_TAG"
        

        ls -ltra
        # Docker build for mysql server
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}" -f Dockerfile_mysql .
        # Unit test
        docker run --name mysql -e MYSQL_ROOT_PASSWORD=pw -d $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}"
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        docker exec mysql mysql -ppw -e "show databases;"
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}"
        
    - name: Build, test, tag, and push WebAPP image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: clo835-finalproject-pg
      run: |
        IMAGE_TAG=WebAPP-$(date +"%Y%m%d%H%M%S")
        echo "IMAGE_TAG: $IMAGE_TAG"
        ls -ltra
        # Docker build for mysql server
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}" -f Dockerfile .
        # Unit test
        export DBHOST=`docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql`
        echo $DBHOST
        export DBPORT=3306
        export DBUSER=root
        export DATABASE=employees
        export DBPWD=pw
        export IMAGE_URL=https://picsum.photos/200/300
        export GROUP_NAME=Group-1
        export SLOGAN=WORKSMARTNOTHARD
        docker run -p 8080:8080 -e DBHOST=$DBHOST -e DBPORT=$DBPORT -e DBUSER=$DBUSER -e DBPWD=$DBPWD -e DATABASE=$DATABASE -e IMAGE_URL=$IMAGE_URL -e GROUP_NAME=$GROUP_NAME -e SLOGAN=$SLOGAN -d $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}"
        docker ps
        echo "Pause for 10 seconds to let container start"
        sleep 10
        docker ps
        curl 127.0.0.1:8080
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:"${IMAGE_TAG}"
